### ISSUE TITLE
スケールできていない？

### ISSUE THREAD

**Issue by FujiHaruka** [realglobe-Inc/sugo-hub#22]
Redis使って冗長構成にしようと思い、こういうコードを書きましたがうまく行きませんでした。コードに問題があるのか、バグなのか、どうなのでしょうか？

server 側
```js
const Hub = require('sugo-hub')
const co = require('co')

co(function * () {
  let hub1 = yield launchHub(3000)
  let hub2 = yield launchHub(3001)
})

function launchHub (port) {
  return co(function * () {
    let hub = Hub({
      storage: {
        redis: {
          url: 'redis://127.0.0.1:6379',
          db: 1
        }
      }
    })
    yield hub.listen(port)
    return hub
  })
}
```

client 側
```js
const Caller = require('sugo-caller')
const Actor = require('sugo-actor')
const { Module } = Actor
const co = require('co')

const ACTOR_PORT = 3001
const CALLER_PORT = 3000

co(function * () {
  {
    let actor = Actor({
      key: 'actor-01',
      protocol: 'http',
      host: `localhost:${ACTOR_PORT}`,
      modules: {
        pinger: new Module({
          ping () {
            console.log('Called ping')
            return 'pong'
          }
        })
      }
    })
    yield actor.connect()
  }

  {
    let caller = Caller({
      protocol: 'http',
      host: `localhost:${CALLER_PORT}`
    })
    let actor = yield caller.connect('actor-01')
    let pinger = actor.get('pinger')
    let pong = yield pinger.ping()
    console.log(pong)
  }
}).catch(e => console.error(e))
```

エラーメッセージ
```
Error: Cannot read property 'emit' of undefined ( event: "sg:remote:perform", data: "{"key":"actor-01","method":"ping","params":[],"module":"pinger","meta":{"types":{}}}" )
    at unlessDone (/home/fujiharuka/playground/sugos-redundant/node_modules/sg-socket-client/lib/extensions/call_extension.js:48:37)
    at unlessDone (/home/fujiharuka/playground/sugos-redundant/node_modules/sg-socket-client/lib/extensions/call_extension.js:33:11)
    at Socket.s.emit (/home/fujiharuka/playground/sugos-redundant/node_modules/sg-socket-client/lib/extensions/call_extension.js:48:13)
    at Socket.onack (/home/fujiharuka/playground/sugos-redundant/node_modules/socket.io-client/lib/socket.js:312:9)
    at Socket.onpacket (/home/fujiharuka/playground/sugos-redundant/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/home/fujiharuka/playground/sugos-redundant/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/fujiharuka/playground/sugos-redundant/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/fujiharuka/playground/sugos-redundant/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/home/fujiharuka/playground/sugos-redundant/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/fujiharuka/playground/sugos-redundant/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
```

**Comment by okunishinishi** [comment]
socketはデフォルトで自分のidと同じ名前のroomを持つ模様。

https://socket.io/docs/rooms-and-namespaces/#default-room


なので、

`actorIO.connected[ actor.socketId ].emit({ /* ... * })`

を

`actorIO.to[ actor.socketId ].emit({ /* ... * })`

に書き換えるとうまくいきそう。

**Comment by okunishinishi** [comment]
問題はackがroom経由だと使えないこと。これさえ直せば良さそう
